spring.application.name=API-analitica
# Configuración de Base de Datos H2
spring.datasource.url=jdbc:h2:file:./data/miscreacionesdb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Para que las tablas se creen automáticamente
spring.jpa.hibernate.ddl-auto=update

# Consola H2 para que veas los datos en el navegador (localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Habilitar la inicialización de la base de datos
spring.sql.init.mode=always
# Opcional: ver los inserts en la consola para confirmar que funcionan
spring.jpa.show-sql=true